export const locations = [
  {
    city: "Bangalore",
    localities: [
      "Adugodi",
      "Agara",
      "Agram",
      "Ashoknagar",
      "B Sk Ii Stage",
      "Banashankari Iii Stage",
      "Banashankari",
      "Bangalore Corporation Building",
      "Bannerghatta Road",
      "Bannerghatta",
      "Basavanagudi",
      "Begur",
      "Bellandur",
      "Bidrahalli",
      "Bangalore Viswavidalaya",
      "Bolare",
      "Bommanahalli",
      "Bommasandra Industrial Estate",
      "Carmelram",
      "Chamrajpet",
      "Chandapura",
      "Chickpet",
      "Chikkalasandra",
      "Chudenapura",
      "Dasarahalli(srinagar)",
      "Deepanjalinagar",
      "Devanagundi",
      "Dharmaram college",
      "Doddakallasandra",
      "Electronics City",
      "Gaviopuram Extension",
      "Girinagar",
      "Gottigere",
      "Governmemnt Electric Factory",
      "Hsr Layout",
      "Hulimavu",
      "J P Nagar",
      "Jayanagar",
      "Jayanagar West",
      "Jayangar III Block",
      "Jp Nagar III Phase",
      "Jp Nagar VIII Phase",
      "Kadugodi",
      "Kannamangala",
      "Kathriguppe",
      "Koramangala I Block",
      "Koramangala",
      "Koramangala Vi Bk",
      "Kumaraswamy Layout",
      "Kumbalagodu",
      "Kumbalgodu Gollahalli",
      "Madhavan Park",
      "Madivala",
      "Mallathahalli",
      "Mavalli",
      "Medimallasandra",
      "Mico Layout",
      "Mount St Joseph",
      "Mundur",
      "Muthanallur",
      "Muthusandra",
      "Nayandahalli",
      "Padmanabhnagar",
      "Pampamahakavi Road",
      "Panathur",
      "Rajarajeshwarinagar",
      "Ramohalli",
      "Rv Niketan",
      "Shanthinagar",
      "St. John’s Medical College",
      "State Bank Of Mysore Colony",
      "Subramanyapura",
      "Thalaghattapura",
      "Thataguni",
      "Tilaknagar",
      "Tyagrajnagar",
      "Vartur",
      "Viveknagar",
      "Whitefield",
      "Wilson Garden",
      "Wipro Limited",
      "Yelachenahalli",
    ],
  },
]
